lua/mini/jump.lua
This is a module named `mini.jump`, implementing the basic functionality of [clever-f](https://github.com/rhysd/clever-f.vim) and a basis for the functionality of [vim-sneak](https://github.com/justinmk/vim-sneak).
~~Would this fit the spirit of this project? Should I also add two-char search like vim-sneak?~~
~~(Note: the implementation is currently a bit buggy, but the basic functionality works)~~
=> mini.jump (clever-f)

doc/mini.txt, lua/mini/fuzzy.lua
- [ x] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [ x] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
Fix key name of `telescope`: "default" -> "default **s** "
=> Fix typo in usage of mini.fuzzy

doc/mini.txt, lua/mini/jump.lua
This PR adds timeout after idle feature, inspired by lightspeed.nvim.
With this feature, you can reset highlights automatically, and start searching for another character easily.
The default value is set to `10^7`, so it won't break behavior compatibility.
=> feat(mini.jump): Add idle timeout to stop jumping automatically

doc/mini.txt, lua/mini/jump.lua, tests/jump_spec.lua
I started using mini.jump recently, and noticed a couple issues.
1. Highlights don't include capital letters, but you still jump to them by default. After a bit of testing, I confirmed this is because I use the `ignorecase` and `smartcase` vim options.
2. Highlights appear when used with an operator, despite the fact that you can't actually perform a repeat.
3. In operator pending mode, we print a spurious `lua MiniJump.jump()` to the statusline.
I made a few commits to polish these up.
Regarding case sensitivity, I personally _like_ that this plugin follows `ignorecase`, and so all I did was fix the disparity between jumping and highlighting. However, it does seem like respecting `ignorecase` in this plugin may not have been intentional. If you'd rather fix this, I would be happy to …
=> Fix mini.jump highlighting & command output

lua/mini/jump2d.lua
I automatically open the quickfix list when using commands like `:grep`/`:vimgrep` using an implementation that hooks into the `QuickFixCmdPost` event, similar to [this implementation](https://vim.fandom.com/wiki/Automatically_open_the_quickfix_window_on_:make).
```vim
autocmd QuickFixCmdPost [^l]* nested cwindow
autocmd QuickFixCmdPost    l* nested lwindow
```
I see that MiniJump2d [attempts to replace](https://github.com/echasnovski/mini.nvim/blob/main/lua/mini/jump2d.lua#L137) the <CR> mapping in a quickfix list. However, sometimes, the mapping is not replaced and hitting `<CR>` in the quickfix list activates MiniJump2d instead of navigating to the file. This may be due to a race condition on when the events are fired. Closing and re-opening the quickfix list "fixes" this problem, …
=> [MiniJump2d] Replace <CR>-mapping based on the FileType event

readmes/mini-bracketed.md
Noticed a small typo. Looking forward to trying out the new module! 🙂
=> fix: typo s/move/bracketed/ in "this link" link

lua/mini/doc.lua
Fixed a behavior that "foo/bar/init.lua" takes precedence over "foo/init.lua" when "foo/bar/init.lua" and "foo/init.lua" exist.
=> fix(doc): Reflects the directory hierarchy.

lua/mini/misc.lua
There is also an API for setting marks but not for opening folds. So it doesn't make sense to use `vim.api.nvim_win_set_cursor()` yet.
=> (mini.misc) Use neovim API for MiniMisc.restore_cursor

lua/mini/starter.lua
This is a simple fix for `mini.starter` not refreshing when Neovim is resized, due to `MiniStarter.refresh()` unintentionally being passed an invalid argument.
=> (mini.starter) Fix refresh on resize

lua/mini/files.lua
I found these typos while browsing the source code ^^'
=> (mini.files) Fix typos on comment

lua/mini/bufremove.lua
When closing the last buffer with `bufremove` it gives you a scratch buffer rather than just a normal buffer. This means if you modify it and run `:confirm q` it won't warn before closing. This can be pretty detrimental especially for people who are used to core vim behavior. By just creating a normal buffer without the `nofile` buffer type we can re-align `mini.bufremove` with the core vim behavior that people may be accustom to. This also remains un-opinionated because it doesn't set any file types or buffer types.
If you don't want this change, it could be a good idea to have a configuration option that allows users to align themselves with the core vim behavior if they are used to it.
This also would resolve #372 confusion
=> (mini.bufremove) create modifiable buffer rather than a scratch buffer

doc/mini-basics.txt, lua/mini/basics.lua
Fixes typo in `mini.basics` help docs for `<M-hjkl>` moves.
=> (mini.basics) Fix typo in help.

doc/mini-test.txt, lua/mini/test.lua, tests/test_test.lua
I like `mini.test`, but I don't particularly like to write lua code as strings, because it looses syntax highlighting/code completion/type checking etc. I started to use this little function and I think it works pretty well. I thought that I can contribute it here.
=> (mini.test) Add `child.lua_func()` method

doc/mini-map.txt, lua/mini/map.lua, tests/test_map.lua
Needed this to avoid orchestrating my other floats around the default 10 z-index. [nvim-treesitter-context](https://github.com/nvim-treesitter/nvim-treesitter-context) has a default of 20 so anyone installing it would run into this issue.
I'm currently using a [fork](https://github.com/nolantait/mini.map) of this on my [configs](https://github.com/nolantait/dotfiles/blob/a0c754859046d513ea6c0ce7ee89b74e4b839f8c/config/nvim/lua/plugins/configs/mini-map.lua#L43) and its working great.
=> (mini.map) FEATURE: Adds zindex as window option

lua/mini/ai.lua
While debugging `mini.ai` I discovered this command and saw that it is referring to a deprecated treesitter command. With this change, the documentation will be accurate again.
=> (mini.ai) Fix outdated treesitter query command in comment.

lua/mini/completion.lua, tests/test_completion.lua
Right now, mini.completion adds "c" to `shortmess` when `set_vim_settings` is enabled to reduce the amount of command line messages printed when completing. This PR also adds "C" to `shortmess` to further silence unnecessary messages. This has also already been referenced in https://github.com/echasnovski/mini.nvim/issues/5#issuecomment-1278554178 before. I've changed the code so that it detects to see if the user is using Neovim 0.9.0 or newer before adding the flag, and I also edited the appropriate tests.
=> (mini.completion) Update `set_vim_settings`'s `shortmess` to hide completion messages

lua/mini/base16.lua, lua/mini/hues.lua
=> (mini.hues) Update CoC diagnostic highlight to link DiagnosticUnderline

doc/mini-surround.txt
=> docs(surround): Fix mini-surround examples doc

lua/mini/base16.lua, lua/mini/hues.lua
=> Update 'coc.nvim' to distinguish LSP 'unused parameter' highlight.

lua/mini/diff.lua
https://github.com/neovim/neovim/pull/28101 renamed nvim__buf_redraw_range to nvim__redraw.
=> fix(diff): update for breaking change on nightly

lua/mini/surround.lua
- [x ] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [x ] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
When reading through docs of mini.surround, I noticed that they explain only one way of defining output specification of surround, with plain strings. Later in examples the docs show that we can also use functions that return output specification. 
So I wanted to add this option to surround specification. And I also added an example with output of a default function call surround.
=> mini.surround: Added explanaition of defining output specification with function to documentation

lua/mini/statusline.lua
`H.get_buf_lsp_clients` will return a map of `client_id:client`. So if we handle it as array, there could be hole in it, and `table.concat` will fail with "invalid value (nil) at index [i] in table for 'concat'".
=> fix(statusline)!: make compute_attached_lsp() depend only number of attached client

doc/mini-extra.txt, lua/mini/extra.lua, tests/test_extra.lua
Reference: This [discussion](https://github.com/echasnovski/mini.nvim/discussions/995)
In my workflow, each project is opened in a `tmux` session. As such, when querying `oldfiles`, I am mostly interested in files inside the current working directory.
`MiniExtra.pickers.oldfiles()` currently does not filter on `cwd`
This PR adds flag "current_dir" to `MiniExtra.pickers.oldfiles()`
=> feat(extra): add flag 'current_dir' to `oldfiles()` picker

lua/mini/hues.lua
`LeapLabelPrimary` and `LeapLabelSecondary` are deprecated, see [b75a86f](https://github.com/ggandor/leap.nvim/commit/b75a86f14ebdb3940460bfd1a02224210eccc698)
If this PR is according to expectations I would like to provide a PR for mini.base16.
Screenshots, typing `sif` on line 1:
Before:
After:
=> fix(hues): leap deprecated highlights, use LeapLabel

lua/mini/base16.lua
`LeapLabelPrimary` and `LeapLabelSecondary` are deprecated, see [b75a86f](https://github.com/ggandor/leap.nvim/commit/b75a86f14ebdb3940460bfd1a02224210eccc698)
Screenshots, typing `sif` on line 1:
Before:
After:
=> fix(base16): leap deprecated highlights, use LeapLabel

lua/mini/icons.lua
I noticed the HCL filetype is missing. This is a filetype that matches with `vim.filetype.match`. I also made sure to follow the guidelines when selecting an icon. Let me know what you think 😄
=> feat(icons): add `hcl` filetype

lua/mini/icons.lua
[Gleam](https://gleam.run/) is a new functional language that runs on Erlang and Javascript targets and I feel like it deserves an icon here for the `gleam` filetype. In the commit i used `nf-fa-star` because I think it looks more authentic to the actual [Gleam logo](https://avatars0.githubusercontent.com/u/36161205?s=400&v=4). If it really has to be from the `nf-md` I'll gladly change it, but I feel like the Font Awesome icon is more like the real logo.
**Example of it in Oil**
=> feat(icons): add gleam filetype icon

TESTING.md
I've really enjoyed your plugins. I have previously been using Plenary's testing harness but I'm starting to play with `mini.test` and noticed a typo in the example as I was going through things. `mini.test` looks really nice so far!
=> docs(TESTING.md): fix typo in example

lua/mini/misc.lua
Use explicit targeting to sync the terminal background. 
Nvim changes standard streams to non-blocking mode, so we should use io.stdout:write to ensure that writes are handled properly (that is, directly addressing the term's standard output).
~~This should address the last remaining bits from #1111:~~
> ~~That's both good (it fixes something) and confusing (it introduces very similar issue for me) news. I'll just focus on the first interpretation :)~~
Let me know how it goes :)
=> fix(misc): target stdout stream explicitly

doc/mini-bracketed.txt, lua/mini/bracketed.lua
Hello! Here is a _very_ small docs fix: adds a missing space so that `[Y` is aligned correctly and renders as highlighted.
Thanks so much for mini.nvim, and your help files are the best around!
=> docs(bracketed): fix typo

lua/mini/pairs.lua
Temporarily toggle `vim.o.lazyredraw = true` while inserting pairs to prevent weird cursor flickering
I reduced the video speed to 1/4. The cursor jumping forth and back drives me nuts))
https://github.com/user-attachments/assets/2ef07b04-cea1-4c51-8535-8502a65ba859
The screen will be redrawn only on the next tick. Similar to your using of  `vim.o.eventignore`
https://github.com/user-attachments/assets/8a902893-6886-42f3-9dd8-345c66eb2a21
=> fix(pairs): consider using `lazyredraw` to prevent cursor flickering

doc/mini.txt, lua/mini/init.lua
Small typo `recepies` to `recipes`
=> docs: fix recipes typo

lua/mini/align.lua, tests/test_align.lua
Prevent undoing previous actions if no change was made in the current alignment iteration. This is very important, for example, when running alignment under a `:normal` command so it can play well with other actions.
=> fix(align): prevent undo if no change was made

lua/mini/icons.lua
Nothing much just added a glyph for the 
`norg` filetype :)
=> feat(icons): add a glyph for `norg` filetype

lua/mini/completion.lua
This PR fixes the error mentioned in [this](https://github.com/echasnovski/mini.nvim/discussions/1681) discussion: Setting up completion + snippets fails.
I added `or item.error` to three locations, and tested on both v0.10.4 and nightly according to the setup used in the discussion.
I tried to copy and modify testcase `prefer snippet from resolved item`. Unfortunately I could not reliably test the premise.
=> fix(completion): check lsp result for both err and error key

lua/mini/misc.lua, tests/test_misc.lua
Hello,
I'm currently developping a small plugin that performs some actions when the current directory is changed. It works by defining autocommands triggered on [`DirChanged`](https://neovim.io/doc/user/autocmd.html#DirChanged) events.
However these autocommands are not triggered by `setup_auto_root`. This is because by default, autocommands are not triggered inside another autocommand ([source](https://neovim.io/doc/user/autocmd.html#autocmd-nested)).
This PR changes that by setting the `nested` option to `true` when creating the autocommand in `setup_auto_root`.
It should not trigger any other events than `DirChanged` and `DirChangedPre` since the callback of `setup_auto_root` basically only calls `vim.fn.chdir()`, and it seems logical to allow those two events to be triggered.
Thanks …
=> feat(misc): trigger nested autocommands in setup_auto_root

doc/mini-colors.txt, lua/mini/colors.lua
=> docs(colors): fix typo in MiniColors.setup()

doc/mini-colors.txt, lua/mini/align.lua, lua/mini/colors.lua, tests/test_align.lua
This fixes a bug introduced in b83127c36cc7a9f3cb9e16f5d9db1231d30c33f9. In summary, these calls started to fail after that commit:
```
MiniAlign.align_strings({})
MiniAlign.align_strings({""})
MiniAlign.align_strings({"", ""})
```
I noticed that a custom picker of mine broke recently, but hadn't had time to chase down what happened until this morning. I use `MiniAlign.align_strings` in a picker.source.show function to pretty things up with live grep. At the start of that picker, there are no items, so `align_strings` was being passed `{}` and erroring out. Prior to the change mentioned above, my picker worked without error.
The following PR addresses the issue. I also added tests (now that I recently learned how to do so with your awesome 'mini.test'—thank you).
=> fix(align): handle empty list and empty strings properly

lua/mini/jump2d.lua
`res.spotter` is already initialized for the `nil` input case.
=> refactor(jump2d): remove two redundant lines of code

lua/mini/ai.lua, lua/mini/surround.lua
This PR makes two things:
- `mini.ai` is now aware of matches with multiple matching nodes
- `mini.ai` now parses on it's own the buffer when there's a need to
Some comments:
> `mini.ai` is now aware of matches with multiple matching nodes
This means that for captures like https://github.com/nvim-treesitter/nvim-treesitter-textobjects/blob/fa32a45fdbab9c9c3bda9ecec9b12dddb221b927/queries/lua/textobjects.scm#L12-L17 (present on the `main` branch of nvim-treesitter-textobjects) the behavior before this change is the following
```lua
--   | the cursor is here
--   v 
a(b, c, d)
-- the user configuration looks like
require("mini.ai").setup {
custom_textobjects = {
F = require("mini.ai").gen_spec.treesitter { a = "@call.outer", i = "@call.inner" },
},
}
-- the user does `viF` and only the `d` …
```
=> feat(ai): take matches with multiple nodes into account

lua/mini/icons.lua, lua/mini/pick.lua, tests/test_icons.lua
This PR aims to improve user experience by using the user's custom mappings for mini.pick's help picker. If users remap their split mappings, then all pickers should respect that.
=> feat(pick): Use user's mappings for builtin help picker

CHANGELOG.md, doc/mini-misc.txt, lua/mini/misc.lua, tests/test_misc.lua
This PR makes `MiniMisc.zoom` return the zoomed state of current buffer: `true` if zoomed in and `false` if zoomed out. This is useful for conditionally applying additional configurations to the window zoomed in. This feature was suggested in <https://github.com/echasnovski/mini.nvim/discussions/1953#discussioncomment-14138773> and also provides a more robust way to check zoomed state compared to that suggested in <https://github.com/echasnovski/mini.nvim/issues/1911#issuecomment-3112985891>. Basic usage:
```lua
local my_zoom = function()
-- Do nothing if zoomed out.
if not MiniMisc.zoom() then return end
vim.wo.winbar = 'my winbar'
-- ...other configurations
end
vim.keymap.set('n', '<Leader>z', my_zoom, { desc = 'Zoom' })
```
=> feat(misc): make `zoom()` return whether zoomed in or out

lua/mini/sessions.lua, tests/test_sessions.lua
Resolve #1967
Before concatenating `global_dir` and filename with `/`, I confirmed that `global_dir` was already normalized (you do that in `H.full_path`. I did not use the `type` returned by the iterator of `vim.fs.dir` because you already check the type in `H.is_readable_file`, so it would be a duplicative check.
=> fix(sessions): support sessions names with leading dot

lua/mini/files.lua
I noticed on windows when trying to browse a file share using a UNC path (//server/share or \\server\share) the leading slash was eaten as part of the file normalization. 
This PR modifies the windows normalization function on windows to allow two leading slashes, but otherwise remove any repeats.
=> fix(files): allow leading // or \\ on windows for UNC paths
